# Generated by Django 2.2.4 on 2020-10-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_manage', '0002_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_progress',
            field=models.IntegerField(null=True),
        ),
    ]
