# Generated by Django 2.2.4 on 2020-10-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_manage', '0004_auto_20201021_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_owner',
            field=models.TextField(default='TBD', max_length=255),
        ),
    ]
